language: cpp
dist: trusty
sudo: required
compiler: gcc
before_install:
  - git clone https://github.com/google/googletest.git
  - git clone https://github.com/glfw/glfw.git
install:
  - apt-get install xorg-dev
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest